version: 1.0.0.{build}
branches:
  only:
  - master
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- cmd: build.cmd
test: off
artifacts:
- path: artifacts/nuget/*
deploy:
- provider: NuGet
  api_key:
    secure: BJIZ1k2V8xaB2U8rS/vM8BJwihpdWE0yhzscE+VTAvPCfEpUvLVV7vfkZCmBpZoK